worker:
	g++  -I /usr/local/include/zookeeper/ -L /usr/local/lib/ worker.cpp -o worker.out -lzookeeper_st
admin:
	g++  -I /usr/local/include/zookeeper/ -L /usr/local/lib/ admin.cpp -o admin.out -lzookeeper_st -fopenmp

